### ISSUE TITLE
I recommend the routes to be under the auth or admin middleware

### ISSUE THREAD

**Issue by tabacitu** [eduardoarandah/Laravel-Backpack-ArcaneDev-LogViewer#2]
I see the routes are registerd by ArcaneDev/LogViewer, and they aren't behind any password-protected middleware.

Wouldn't it be better to instruct people to place the routes under the same middleware as Backpack? Otherwise anybody can see the logs, without being logged in.

**Comment by eduardoarandah** [comment]
Thanks for pointing that out, I forgot adding that part. 

Just added this: https://github.com/eduardoarandah/Laravel-Backpack-ArcaneDev-LogViewer#configure-middleware
